site_name: Yantra Launcher Wiki
site_description: 'Documentation for using Yantra Launcher'
site_author: 'The Yantra Launcher Community'
docs_dir: web/
repo_name: 'coderGtm/yantra-app-launcher'
repo_url: 'https://github.com/coderGtm/yantra-app-launcher'
edit_uri: 'edit/main/docs/'
nav:
    - Home: docs/index.md
    - Quickstart: docs/quickstart.md
    - Commands Overview: docs/commands-overview.md
    - Commands:
        - Essentials:
            - help: docs/commands/help.md
            - exit: docs/commands/exit.md
            - reset: docs/commands/reset.md
            - clear: docs/commands/clear.md
            - history: docs/commands/history.md
            - support: docs/commands/support.md
            - feedback: docs/commands/feedback.md
            - cmdrequest: docs/commands/cmdrequest.md
            - community: docs/commands/community.md
        - App Management:
            - launch: docs/commands/launch.md
            - launchf: docs/commands/launchf.md
            - list: docs/commands/list.md
            - info: docs/commands/info.md
            - infof: docs/commands/infof.md
            - uninstall: docs/commands/uninstall.md
        - Productivity:
            - todo: docs/commands/todo.md
            - notepad: docs/commands/notepad.md
            - calc: docs/commands/calc.md
            - alarm: docs/commands/alarm.md
            - timer: docs/commands/timer.md
            - time: docs/commands/time.md
            - screentime: docs/commands/screentime.md
        - Communication:
            - call: docs/commands/call.md
            - email: docs/commands/email.md
            - text: docs/commands/text.md
            - translate: docs/commands/translate.md
        - Search & Web:
            - search: docs/commands/search.md
            - web: docs/commands/web.md
            - gupt: docs/commands/gupt.md
            - internet: docs/commands/internet.md
            - speedtest: docs/commands/speedtest.md
            - weather: docs/commands/weather.md
            - news: docs/commands/news.md
            - dict: docs/commands/dict.md
        - System:
            - settings: docs/commands/settings.md
            - battery: docs/commands/battery.md
            - sysinfo: docs/commands/sysinfo.md
            - lock: docs/commands/lock.md
            - flash: docs/commands/flash.md
            - vibe: docs/commands/vibe.md
            - bluetooth: docs/commands/bluetooth.md
            - setclr: docs/commands/setclr.md
            - theme: docs/commands/theme.md
            - bg: docs/commands/bg.md
            - username: docs/commands/username.md
        - Automation:
            - alias: docs/commands/alias.md
            - unalias: docs/commands/unalias.md
            - scripts: docs/commands/scripts.md
            - run: docs/commands/run.md
            - init: docs/commands/init.md
            - termux: docs/commands/termux.md
            - sleep: docs/commands/sleep.md
            - notify: docs/commands/notify.md
        - File System:
            - ls: docs/commands/ls.md
            - cd: docs/commands/cd.md
            - pwd: docs/commands/pwd.md
            - open: docs/commands/open.md
        - Media & Fun:
            - music: docs/commands/music.md
            - sfx: docs/commands/sfx.md
            - tts: docs/commands/tts.md
            - quote: docs/commands/quote.md
            - bored: docs/commands/bored.md
            - ai: docs/commands/ai.md
            - pro: docs/commands/pro.md
    - Frequently Asked Questions: docs/faq.md
    
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  favicon: img/favicon.ico
  logo: img/logo.png
  icon:
    repo: fontawesome/brands/github
  features:
    - content.action.edit
    - content.code.copy

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/coderGtm/yantra-app-launcher
      name: View on GitHub
    - icon: fontawesome/brands/discord
      link: https://discord.gg/YW7hYbPrTh
      name: Official Discord Community
    - icon: fontawesome/brands/reddit-alien
      link: https://www.reddit.com/r/YantraLauncher/
      name: Yantra Launcher subreddit

plugins:
  - git-revision-date-localized:
      type: timeago
  - git-committers:
      repository: coderGtm/yantra-app-launcher
      branch: main
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
